# Site settings
name: Fivever
email: 1075263474@qq.com
author: Jason Xiong
url: http://www.fivever.github.io
resume_site: 
github: https://github.com/fivever/
baseurl: 
description: Jason Xiong's Personal Blogs
meta_description: 
motto: 极限尤可突破 至臻亦不可止
banner: 思想 信任 自知

permalink: /:categories/:title/
# permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Fivever

# Build settings
markdown: kramdown

