# Site settings
name: Fivever
email: 1075263474@qq.com
author: Freud Kang
url: http://www.fivever.github.io
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/fivever/
baseurl: 
description: Actually, less is more!
meta_description: 
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Fivever

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

